/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#d2bbff",
        "secondary-container": "#316bf3",
        "outline": "#7b7487",
        "tertiary-fixed-dim": "#ffb784",
        "surface-container-low": "#f9f1ff",
        "surface-container": "#f3ebfa",
        "surface-dim": "#dfd7e6",
        "on-tertiary-fixed-variant": "#713700",
        "secondary-fixed-dim": "#b4c5ff",
        "on-surface": "#1d1a24",
        "on-tertiary-container": "#ffe0cd",
        "background": "#fef7ff",
        "on-primary-container": "#ede0ff",
        "primary-fixed": "#eaddff",
        "tertiary-container": "#a15100",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#25005a",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#d2bbff",
        "on-secondary-container": "#fefcff",
        "on-surface-variant": "#4a4455",
        "surface-bright": "#fef7ff",
        "secondary-fixed": "#dbe1ff",
        "error": "#ba1a1a",
        "surface": "#fef7ff",
        "surface-variant": "#e8dfee",
        "secondary": "#0051d5",
        "inverse-on-surface": "#f6eefc",
        "inverse-surface": "#332f39",
        "tertiary": "#7d3d00",
        "on-secondary-fixed-variant": "#003ea8",
        "tertiary-fixed": "#ffdcc6",
        "surface-container-high": "#ede5f4",
        "on-error-container": "#93000a",
        "on-background": "#1d1a24",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#5a00c6",
        "on-secondary": "#ffffff",
        "primary": "#630ed4",
        "surface-tint": "#732ee4",
        "outline-variant": "#ccc3d8",
        "primary-container": "#7c3aed",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#301400",
        "on-secondary-fixed": "#00174b",
        "surface-container-highest": "#e8dfee",
        "error-container": "#ffdad6"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "base": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "gutter": "24px",
        "xl": "48px",
        "container-max": "1200px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["22px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-lg": ["30px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display": ["46px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["10px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}
